[package]
name = "aginci_core"
version = "0.1.0"
edition = "2024"

[features]
default = ["step_executor"]
step_executor = []

[dependencies]
async-trait = "0.1.88"
color-eyre = "0.6.5"
enum_dispatch = "0.3.13"
paste = "1.0.15"
schemars = { version = "1.0.4", features = ["preserve_order"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
visible = "0.0.1"
