/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTokenCreateResponse {
    /// Store the token securely, as it will not be shown again
    #[serde(rename = "token")]
    pub token: String,
}

impl AccessTokenCreateResponse {
    pub fn new(token: String) -> AccessTokenCreateResponse {
        AccessTokenCreateResponse {
            token,
        }
    }
}

