/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTokenCreateBody {
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<models::Scope>,
}

impl AccessTokenCreateBody {
    pub fn new(display_name: String, scopes: Vec<models::Scope>) -> AccessTokenCreateBody {
        AccessTokenCreateBody {
            display_name,
            scopes,
        }
    }
}

