/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateOrgSecretBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "secret")]
    pub secret: String,
}

impl CreateOrgSecretBody {
    pub fn new(name: String, secret: String) -> CreateOrgSecretBody {
        CreateOrgSecretBody {
            name,
            secret,
        }
    }
}

