/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectBody {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "repository")]
    pub repository: Box<models::CreateProjectBodyRepository>,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl CreateProjectBody {
    pub fn new(name: String, repository: models::CreateProjectBodyRepository, slug: String) -> CreateProjectBody {
        CreateProjectBody {
            name,
            repository: Box::new(repository),
            slug,
        }
    }
}

