/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateProjectBodyRepository {
    #[serde(rename = "source")]
    pub source: models::ProjectRepositorySource,
    #[serde(rename = "url")]
    pub url: String,
}

impl CreateProjectBodyRepository {
    pub fn new(source: models::ProjectRepositorySource, url: String) -> CreateProjectBodyRepository {
        CreateProjectBodyRepository {
            source,
            url,
        }
    }
}

