/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedOneOf3 {
    #[serde(rename = "body")]
    pub body: Box<models::DetailedOfflineWorker>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl DetailedOneOf3 {
    pub fn new(body: models::DetailedOfflineWorker, r#type: Type) -> DetailedOneOf3 {
        DetailedOneOf3 {
            body: Box::new(body),
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "offline-worker")]
    OfflineWorker,
}

impl Default for Type {
    fn default() -> Type {
        Self::OfflineWorker
    }
}

