/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Detailed {
    DetailedOneOf(Box<models::DetailedOneOf>),
    DetailedOneOf1(Box<models::DetailedOneOf1>),
    DetailedOneOf2(Box<models::DetailedOneOf2>),
    DetailedOneOf3(Box<models::DetailedOneOf3>),
    DetailedOneOf4(Box<models::DetailedOneOf4>),
}

impl Default for Detailed {
    fn default() -> Self {
        Self::DetailedOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "job-failed")]
    JobFailed,
    #[serde(rename = "received-invitation")]
    ReceivedInvitation,
    #[serde(rename = "role-changed")]
    RoleChanged,
    #[serde(rename = "offline-worker")]
    OfflineWorker,
    #[serde(rename = "other")]
    Other,
}

impl Default for Type {
    fn default() -> Type {
        Self::JobFailed
    }
}

