/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedInvitationEvent {
    #[serde(rename = "invitation")]
    pub invitation: Box<models::Invitation>,
}

impl DetailedInvitationEvent {
    pub fn new(invitation: models::Invitation) -> DetailedInvitationEvent {
        DetailedInvitationEvent {
            invitation: Box::new(invitation),
        }
    }
}

