/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedJobFail {
    #[serde(rename = "job")]
    pub job: serde_json::Value,
}

impl DetailedJobFail {
    pub fn new(job: serde_json::Value) -> DetailedJobFail {
        DetailedJobFail {
            job,
        }
    }
}

