/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedRoleChange {
    #[serde(rename = "new_role")]
    pub new_role: models::OrganizationRole,
    #[serde(rename = "old_role")]
    pub old_role: models::OrganizationRole,
    #[serde(rename = "organization")]
    pub organization: Box<models::SimpleOrganization>,
    #[serde(rename = "user")]
    pub user: String,
}

impl DetailedRoleChange {
    pub fn new(new_role: models::OrganizationRole, old_role: models::OrganizationRole, organization: models::SimpleOrganization, user: String) -> DetailedRoleChange {
        DetailedRoleChange {
            new_role,
            old_role,
            organization: Box::new(organization),
            user,
        }
    }
}

