/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EditNotificationBody {
    #[serde(rename = "status")]
    pub status: models::NotificationStatus,
}

impl EditNotificationBody {
    pub fn new(status: models::NotificationStatus) -> EditNotificationBody {
        EditNotificationBody {
            status,
        }
    }
}

