/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinishRegistrationResponse {
    /// Access token that can be used to authenticate directly to Apache Pulsar
    #[serde(rename = "access_token")]
    pub access_token: String,
    /// Conenction string that should be used to connect to Apache Pulsar
    #[serde(rename = "connection_string")]
    pub connection_string: String,
}

impl FinishRegistrationResponse {
    pub fn new(access_token: String, connection_string: String) -> FinishRegistrationResponse {
        FinishRegistrationResponse {
            access_token,
            connection_string,
        }
    }
}

