/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinishRegistrationBody {
    /// Token that the user generated using `POST /api/system/runners`
    #[serde(rename = "token")]
    pub token: String,
}

impl FinishRegistrationBody {
    pub fn new(token: String) -> FinishRegistrationBody {
        FinishRegistrationBody {
            token,
        }
    }
}

