/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Member {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "role")]
    pub role: models::OrganizationRole,
}

impl Member {
    pub fn new(_id: String, email: String, name: String, role: models::OrganizationRole) -> Member {
        Member {
            _id,
            email,
            name,
            role,
        }
    }
}

