/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NotificationStatus {
    #[serde(rename = "unread")]
    Unread,
    #[serde(rename = "read")]
    Read,
    #[serde(rename = "dismissed")]
    Dismissed,

}

impl std::fmt::Display for NotificationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unread => write!(f, "unread"),
            Self::Read => write!(f, "read"),
            Self::Dismissed => write!(f, "dismissed"),
        }
    }
}

impl Default for NotificationStatus {
    fn default() -> NotificationStatus {
        Self::Unread
    }
}

