/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrganizationRole {
    #[serde(rename = "viewer")]
    Viewer,
    #[serde(rename = "member")]
    Member,
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "owner")]
    Owner,

}

impl std::fmt::Display for OrganizationRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Viewer => write!(f, "viewer"),
            Self::Member => write!(f, "member"),
            Self::Admin => write!(f, "admin"),
            Self::Owner => write!(f, "owner"),
        }
    }
}

impl Default for OrganizationRole {
    fn default() -> OrganizationRole {
        Self::Viewer
    }
}

