/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Organization {
    #[serde(rename = "_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _id: Option<Option<String>>,
    #[serde(rename = "avatar_email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_email: Option<Option<String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "members")]
    pub members: Vec<models::Membership>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl Organization {
    pub fn new(description: String, members: Vec<models::Membership>, name: String, slug: String) -> Organization {
        Organization {
            _id: None,
            avatar_email: None,
            description,
            members,
            name,
            slug,
        }
    }
}

