/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PublicProject : Project object that can be safely sent to the client
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicProject {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "repository")]
    pub repository: Box<models::PublicProjectRepository>,
    #[serde(rename = "slug")]
    pub slug: String,
}

impl PublicProject {
    /// Project object that can be safely sent to the client
    pub fn new(_id: String, name: String, organization_id: String, repository: models::PublicProjectRepository, slug: String) -> PublicProject {
        PublicProject {
            _id,
            name,
            organization_id,
            repository: Box::new(repository),
            slug,
        }
    }
}

