/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegenerateSecretResponse {
    #[serde(rename = "webhook_secret")]
    pub webhook_secret: String,
}

impl RegenerateSecretResponse {
    pub fn new(webhook_secret: String) -> RegenerateSecretResponse {
        RegenerateSecretResponse {
            webhook_secret,
        }
    }
}

