/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterRunnerBody {
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "host_os_type")]
    pub host_os_type: models::HostOs,
}

impl RegisterRunnerBody {
    pub fn new(display_name: String, host_os_type: models::HostOs) -> RegisterRunnerBody {
        RegisterRunnerBody {
            display_name,
            host_os_type,
        }
    }
}

