/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterRunnerResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl RegisterRunnerResponse {
    pub fn new(id: String, success: bool, token: String, uuid: String) -> RegisterRunnerResponse {
        RegisterRunnerResponse {
            id,
            success,
            token,
            uuid,
        }
    }
}

