/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Runner {
    #[serde(rename = "_id")]
    pub _id: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "host_arch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host_arch: Option<Option<String>>,
    #[serde(rename = "host_os", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host_os: Option<Option<String>>,
    #[serde(rename = "host_os_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host_os_type: Option<Option<models::HostOs>>,
    #[serde(rename = "host_os_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host_os_version: Option<Option<String>>,
    #[serde(rename = "last_ping", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_ping: Option<Option<String>>,
    #[serde(rename = "runner_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub runner_version: Option<Option<String>>,
    #[serde(rename = "token_hash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token_hash: Option<Option<String>>,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
}

impl Runner {
    pub fn new(_id: String, display_name: String, uuid: uuid::Uuid) -> Runner {
        Runner {
            _id,
            display_name,
            host_arch: None,
            host_os: None,
            host_os_type: None,
            host_os_version: None,
            last_ping: None,
            runner_version: None,
            token_hash: None,
            uuid,
        }
    }
}

