/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScopeTypeOneOf : Allows access to the user account
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScopeTypeOneOf {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ScopeTypeOneOf {
    /// Allows access to the user account
    pub fn new(r#type: Type) -> ScopeTypeOneOf {
        ScopeTypeOneOf {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user")]
    User,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}

