/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Scope {
    #[serde(rename = "permission")]
    pub permission: models::Permission,
    #[serde(rename = "scope")]
    pub scope: Box<models::ScopeType>,
}

impl Scope {
    pub fn new(permission: models::Permission, scope: models::ScopeType) -> Scope {
        Scope {
            permission,
            scope: Box::new(scope),
        }
    }
}

