/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScopeTypeOneOf2 : Allows access to an organization
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScopeTypeOneOf2 {
    /// Allows access to an organization
    #[serde(rename = "slug")]
    pub slug: String,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl ScopeTypeOneOf2 {
    /// Allows access to an organization
    pub fn new(slug: String, r#type: Type) -> ScopeTypeOneOf2 {
        ScopeTypeOneOf2 {
            slug,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "org")]
    Org,
}

impl Default for Type {
    fn default() -> Type {
        Self::Org
    }
}

