/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ScopeType {
    ScopeTypeOneOf(Box<models::ScopeTypeOneOf>),
    ScopeTypeOneOf1(Box<models::ScopeTypeOneOf1>),
    ScopeTypeOneOf2(Box<models::ScopeTypeOneOf2>),
}

impl Default for ScopeType {
    fn default() -> Self {
        Self::ScopeTypeOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "global")]
    Global,
    #[serde(rename = "org")]
    Org,
}

impl Default for Type {
    fn default() -> Type {
        Self::User
    }
}

