/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecretScope {
    #[serde(rename = "organization")]
    Organization,
    #[serde(rename = "project")]
    Project,

}

impl std::fmt::Display for SecretScope {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Organization => write!(f, "organization"),
            Self::Project => write!(f, "project"),
        }
    }
}

impl Default for SecretScope {
    fn default() -> SecretScope {
        Self::Organization
    }
}

