/*
 * server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ServerRole {
    #[serde(rename = "readonly")]
    Readonly,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "admin")]
    Admin,

}

impl std::fmt::Display for ServerRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Readonly => write!(f, "readonly"),
            Self::User => write!(f, "user"),
            Self::Admin => write!(f, "admin"),
        }
    }
}

impl Default for ServerRole {
    fn default() -> ServerRole {
        Self::Readonly
    }
}

