[package]
name = "librunner"
version = "0.1.0"
edition = "2024"

[dependencies]
aginci_core = { version = "0.1.0", path = "../aginci_core" }
color-eyre = "0.6.5"
tokio = { version = "1.46.1", features = ["full"] }
